Phongo Clap RT: geo::Plane Class Reference
geo::Plane Class Reference
Inherits from shape. Implements functionability for plane shape and its materials and the ray-plane intersections algorithms.
#include <Plane.h>
Public Member Functions
Plane ()
Default constructor for the plane. If no arguments passed it will be initialised with distance(5) n(1,1,1)
Plane (float _distance, ngl::Vec3 _n, ngl::Colour _c)
This constructor reads some arguments and pass them to the private interface.
Plane (float _distance, ngl::Vec3 _n, ngl::Colour _c1, ngl::Colour _c2)
This constructor reads some arguments and pass them to the private interface. For checkerboard planes.
virtual float getIntersection (geo::Ray &_ray)
Virtual method that implements the ray-plane intersection.
virtual ngl::Vec3 getNormalAt (ngl::Vec3 _p)
Simple getter that returns the normal of the plane.
virtual ngl::Colour getColour ()
Returns the colour for plain objects, in other words for non-checkerboard planes.
virtual ngl::Colour getColour (ngl::Vec3 &_isect)
Returns the colour for checker-board planes. This will imply passing an intersection point in world space so that we can make the right calculations to see whether we must return the colour1 or colour2.
Public Member Functions inherited from geo::Shape
void hasRefraction (float _ior, float _transparency, float _diffuse_intensity)
Sets parameters related to refraction, this will be given to the Material class.
void hasReflection (float _refl_intensity, float _diffuse_intensity)
Sets reflection attributes.
Material * getMaterial ()
Returns the material attached to a shape object. This is useful for querying or changing private interface, that's why it is not const.
char getType ()
Derived classes will be Spheres or Planes, I will store the type of geometry in this attribute.
Private Attributes
float m_distance
Distance from the origin the plane is located at.
ngl::Vec3 m_n
Normal of the plane.
Additional Inherited Members
Protected Attributes inherited from geo::Shape
char m_type
Type of geometric object it is.
ngl::Colour m_colour
Colour of the shape.
Material * m_material
Material attached to the Shape object.
Detailed Description
Inherits from shape. Implements functionability for plane shape and its materials and the ray-plane intersections algorithms.
Author
Ramon Blanquer
Todo:
Implement new ways to instanciate a plane, ie specifying three points, or one point and a normal
Definition at line 22 of file Plane.h.
Constructor & Destructor Documentation
geo::Plane::Plane ()
Default constructor for the plane. If no arguments passed it will be initialised with distance(5) n(1,1,1)
Definition at line 14 of file Plane.cpp.
References geo::Shape::m_colour, geo::Shape::m_material, and geo::Shape::m_type.
              : m_distance(5.0f), m_n(ngl::Vec3(1,1,1))
 {
   m_colour = ngl::Colour(1,0,0);
   m_type='p';
   Material* mat = new Material(ngl::Colour(1,1,1,1), ngl::Colour(0,0,0,1));
   m_material = mat;
 }
geo::Plane::Plane (float _distance, ngl::Vec3 _n, ngl::Colour _c)
This constructor reads some arguments and pass them to the private interface.
Parameters
[in] _distance Distance from the origin the plane is located at.
[in] _n Normal of the plane.
[in] _c Plain colour of the plane.
Definition at line 22 of file Plane.cpp.
References geo::Shape::m_colour, m_distance, geo::Shape::m_material, m_n, and geo::Shape::m_type.
 {
   m_distance = _distance;
   m_colour = _c;
   m_type='p';
   Material* mat = new Material(_c);
   m_material = mat;
   if(_n.length() > 1.01 || _n.length() < 0.99)
   {
     _n.normalize();
     m_n = _n;
   }
   else
   {
     m_n = _n;
   }
 }
geo::Plane::Plane (float _distance, ngl::Vec3 _n, ngl::Colour _c1, ngl::Colour _c2)
This constructor reads some arguments and pass them to the private interface. For checkerboard planes.
Parameters
[in] _distance Distance from the origin the plane is located at.
[in] _n Primary colour of the checkerboard.
[in] _c1 Secondary colour of the checkerboard.
Definition at line 42 of file Plane.cpp.
References geo::Shape::m_colour, m_distance, geo::Shape::m_material, m_n, and geo::Shape::m_type.
 {
   m_distance = _distance;
   m_colour = _c1;
   m_type='p';
   Material* mat = new Material(_c1, _c2);
   m_material = mat;
   if(_n.length() > 1.01 || _n.length() < 0.99)
   {
     _n.normalize();
     m_n = _n;
   }
   else
   {
     m_n = _n;
   }
 }
Member Function Documentation
ngl::Colour geo::Plane::getColour () virtual
Returns the colour for plain objects, in other words for non-checkerboard planes.
Returns
The colour of the plane
Implements geo::Shape.
Definition at line 85 of file Plane.cpp.
References geo::Shape::m_material, and Material::objColour().
 {
   return m_material->objColour();
 }
ngl::Colour geo::Plane::getColour (ngl::Vec3 & _isect) virtual
Returns the colour for checker-board planes. This will imply passing an intersection point in world space so that we can make the right calculations to see whether we must return the colour1 or colour2.
Parameters
[in] _isect Position in world space of the intersecting point.
Returns
The colour of the plane at the intersection point
Implements geo::Shape.
Definition at line 90 of file Plane.cpp.
References Material::m_isChecker, geo::Shape::m_material, and Material::objColour().
 {
   if (m_material->m_isChecker)
   {
     return m_material->objColour(_isect);
   }
   else
   {
     return m_material->objColour();
   }
 }
float geo::Plane::getIntersection (geo::Ray & _ray) virtual
Virtual method that implements the ray-plane intersection.
Parameters
[in] _ray Ray that will be used to solve the equation for finding the "t" parameter of the ray that satisfies that this point is shared by both ray and plane aka intersection point.
Returns
The 't' parameter from the R = O + t * d equation form of the line, thus the intersection point.
Implements geo::Shape.
Definition at line 62 of file Plane.cpp.
References geo::Ray::getDirection(), geo::Ray::getOrigin(), m_distance, and m_n.
 {
   ngl::Vec3 ray_dir = _ray.getDirection();
   float a = ray_dir.dot(m_n);
   if(a == 0)
   {
     // ray is paralel
     return -1;
   }
   else
   {
     double b = m_n.dot(_ray.getOrigin() + (-(m_distance*m_n)));
     return -1*b/a;
   }
 }
ngl::Vec3 geo::Plane::getNormalAt (ngl::Vec3 _p) virtual
Simple getter that returns the normal of the plane.
Returns
The normal of the plane
Implements geo::Shape.
Definition at line 80 of file Plane.cpp.
References m_n.
 {
   return m_n;
 }
Member Data Documentation
float geo::Plane::m_distance private
Distance from the origin the plane is located at.
Definition at line 72 of file Plane.h.
ngl::Vec3 geo::Plane::m_n private
Normal of the plane.
Definition at line 76 of file Plane.h.
The documentation for this class was generated from the following files:
FinalSubmission/include/Plane.h
FinalSubmission/src/Plane.cpp