Phongo Clap RT: geo::Sphere Class Reference
geo::Sphere Class Reference
Class that hold an implicit definition of a sphere through center and radius parameters. It also implements a method for finding intersections.
#include <Sphere.h>
Public Member Functions
Sphere ()
Sphere ctor, by default it will instanciate a 1 unit radius sphere in the origin (0,0,0).
Sphere (ngl::Vec3 _center, float _radius, ngl::Colour _colour)
Sphere ctor using a radius and a center.
~Sphere ()
Destructor so that all memory is freed.
void setRadius (float _radius)
Setter for the radius.
void setCenter (ngl::Vec3 _center)
Setter for the center.
float getRadius () const
Returns radius of a sphere.
ngl::Vec3 getCenter () const
Returns center of a sphere.
virtual float getIntersection (geo::Ray &_ray)
Calculates the intersection of the passed ray with the sphere according to the parametric form of a ray: R(t) = P + t * (Q - P)
virtual ngl::Vec3 getNormalAt (ngl::Vec3 _p)
Calculates what the normal is at a given point of a sphere. It doesn't check whether it is on the surface or not because that point will be passed through an intersection which we are sure about.
virtual ngl::Colour getColour ()
Gets colour of the sphere through its material object.
virtual ngl::Colour getColour (ngl::Vec3 &_isect)
Gets colour of the sphere through its material object.
Public Member Functions inherited from geo::Shape
void hasRefraction (float _ior, float _transparency, float _diffuse_intensity)
Sets parameters related to refraction, this will be given to the Material class.
void hasReflection (float _refl_intensity, float _diffuse_intensity)
Sets reflection attributes.
Material * getMaterial ()
Returns the material attached to a shape object. This is useful for querying or changing private interface, that's why it is not const.
char getType ()
Derived classes will be Spheres or Planes, I will store the type of geometry in this attribute.
Private Attributes
ngl::Vec3 m_center
Center of the sphere, in world space coordinates.
double m_radius
Radius of the sphere.
Additional Inherited Members
Protected Attributes inherited from geo::Shape
char m_type
Type of geometric object it is.
ngl::Colour m_colour
Colour of the shape.
Material * m_material
Material attached to the Shape object.
Detailed Description
Class that hold an implicit definition of a sphere through center and radius parameters. It also implements a method for finding intersections.
Author
Ramon Blanquer
Todo:
Implement colour on the sphere
Definition at line 23 of file Sphere.h.
Constructor & Destructor Documentation
geo::Sphere::Sphere () inline
Sphere ctor, by default it will instanciate a 1 unit radius sphere in the origin (0,0,0).
Definition at line 30 of file Sphere.h.
References geo::Shape::m_colour, geo::Shape::m_material, and geo::Shape::m_type.
            : m_center(ngl::Vec3(1,1,1)), m_radius(2.0f)
   {
     m_type = 's';
     m_colour = ngl::Colour(1,1,0,1);
     Material* mat = new Material(ngl::Colour(1,1,0,0));
     m_material = mat;
   }
geo::Sphere::Sphere (ngl::Vec3 _center, float _radius, ngl::Colour _colour) inline
Sphere ctor using a radius and a center.
Parameters
[in] _center The position in where the sphere is positioned.
[in] _radius The radius in scene units of the sphere object.
[in] _colour The colour of the Sphere
Definition at line 43 of file Sphere.h.
References geo::Shape::m_colour, geo::Shape::m_material, and geo::Shape::m_type.
                                                              : m_center(_center), m_radius(_radius)
    {
      m_type = 's';
      m_colour = _colour;
      Material* mat = new Material(_colour);
      m_material = mat;
    }
geo::Sphere::~Sphere () inline
Destructor so that all memory is freed.
Definition at line 53 of file Sphere.h.
 {};
Member Function Documentation
ngl::Vec3 geo::Sphere::getCenter () const inline
Returns center of a sphere.
Returns
The center of a sphere.
Definition at line 77 of file Sphere.h.
References m_center.
 {return m_center;}
virtual ngl::Colour geo::Sphere::getColour () inline virtual
Gets colour of the sphere through its material object.
Parameters
[in] _p The position in the surface of the spehere where we calculate the normal.
Returns
The colour of the sphere
Implements geo::Shape.
Definition at line 99 of file Sphere.h.
References Material::m_colour1, and geo::Shape::m_material.
 {return m_material->m_colour1;}
virtual ngl::Colour geo::Sphere::getColour (ngl::Vec3 & _isect) inline virtual
Gets colour of the sphere through its material object.
Parameters
[in] _p The position in the surface of the spehere where we calculate the normal.
Returns
The colour of the sphere
Implements geo::Shape.
Definition at line 105 of file Sphere.h.
References Material::m_colour1, and geo::Shape::m_material.
 {return m_material->m_colour1;}
float geo::Sphere::getIntersection (geo::Ray & _ray) virtual
Calculates the intersection of the passed ray with the sphere according to the parametric form of a ray: R(t) = P + t * (Q - P)
Parameters
[in] _ray
Returns
The distance from the origin of the ray where it intersects the sphere.
Implements geo::Shape.
Definition at line 14 of file Sphere.cpp.
References getCenter(), geo::Ray::getDirection(), geo::Ray::getOrigin(), and getRadius().
   {
     float ray_origin_x = ray.getOrigin().m_x;
     float ray_origin_y = ray.getOrigin().m_y;
     float ray_origin_z = ray.getOrigin().m_z;
     float ray_direction_x = ray.getDirection().m_x;
     float ray_direction_y = ray.getDirection().m_y;
     float ray_direction_z = ray.getDirection().m_z;
     float sphere_center_x = this->getCenter().m_x;
     float sphere_center_y = this->getCenter().m_y;
     float sphere_center_z = this->getCenter().m_z;
     //float a = 1;
     float b = (2*(ray_origin_x - sphere_center_x)*ray_direction_x)
             + (2*(ray_origin_y - sphere_center_y)*ray_direction_y)
             + (2*(ray_origin_z - sphere_center_z)*ray_direction_z);
     float c = pow(ray_origin_x - sphere_center_x, 2)
             + pow(ray_origin_y - sphere_center_y, 2)
             + pow(ray_origin_z - sphere_center_z, 2)
             - (this->getRadius()*this->getRadius());
     float discriminant = b*b - 4*c;
     if(discriminant > 0)
     {
       //ray intersects sphere
       // first root
       float root_1 = ((-1*b - sqrt(discriminant))/2) - 0.000001;
       if (root_1 > 0)
       {
         return root_1;
       }
       else
       {
         // second root is the smallest positive root
         float root_2 = ((sqrt(discriminant)-b)/2) - 0.000001;
         return root_2;
       }
     }
     else
     {
       return -1;
     }
     /*
     // from Wikipedia: http://en.wikipedia.org/wiki/Line%E2%80%93sphere_intersection
     ngl::Vec3 diff;
     diff = ray.getOrigin() - this->getCenter();
     //float a = 1;
     float b = 2 * diff.dot(ray.getDirection());
     float c =   pow(ray.getOrigin().m_x - this->getCenter().m_x,2)
               + pow(ray.getOrigin().m_y - this->getCenter().m_y,2)
               + pow(ray.getOrigin().m_z - this->getCenter().m_z,2)
               - (this->getRadius()*this->getRadius());
     //float c = diff.dot(diff) - pow(this->getRadius(),2);
     float discriminant = b * b - 4 * c;
     if (discriminant < 0) {return -1;}
     else if (discriminant == 0) {return - 0.5 * b;}
     else {return - 0.5 * (b - sqrt(discriminant));}*/
   }
ngl::Vec3 geo::Sphere::getNormalAt (ngl::Vec3 _p) virtual
Calculates what the normal is at a given point of a sphere. It doesn't check whether it is on the surface or not because that point will be passed through an intersection which we are sure about.
Parameters
[in] _p The position in the surface of the spehere where we calculate the normal.
Returns
The normal of the sphere at a given point.
Implements geo::Shape.
Definition at line 89 of file Sphere.cpp.
References m_center.
   {
     ngl::Vec3 normal;
     normal = _p - m_center;
     normal.normalize();
     return normal;
   }
float geo::Sphere::getRadius () const inline
Returns radius of a sphere.
Returns
The radius of a sphere.
Definition at line 72 of file Sphere.h.
References m_radius.
 {return m_radius;}
void geo::Sphere::setCenter (ngl::Vec3 _center) inline
Setter for the center.
Parameters
[in] _center Center of the sphere.
Definition at line 65 of file Sphere.h.
References m_center.
 {m_center = _center;}
void geo::Sphere::setRadius (float _radius) inline
Setter for the radius.
Parameters
[in] _center The radius of the sphere.
Definition at line 60 of file Sphere.h.
References m_radius.
 {m_radius = _radius;}
Member Data Documentation
ngl::Vec3 geo::Sphere::m_center private
Center of the sphere, in world space coordinates.
Definition at line 111 of file Sphere.h.
double geo::Sphere::m_radius private
Radius of the sphere.
Definition at line 115 of file Sphere.h.
The documentation for this class was generated from the following files:
FinalSubmission/include/Sphere.h
FinalSubmission/src/Sphere.cpp